-- MySQL Script generated by MySQL Workbench
-- Sun Nov 29 19:43:31 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ecokat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecokat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecokat` DEFAULT CHARACTER SET utf8 ;
USE `ecokat` ;

-- -----------------------------------------------------
-- Table `ecokat`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecokat`.`category` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `create_timw` DATETIME NULL,
  `updte_time` DATETIME NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecokat`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecokat`.`author` (
  `author_id` INT NOT NULL AUTO_INCREMENT,
  `author_name` VARCHAR(45) NULL,
  `book_id` INT NULL,
  PRIMARY KEY (`author_id`),
  INDEX `fk_book_author_id_idx` (`book_id` ASC),
  CONSTRAINT `fk_book_author_id`
    FOREIGN KEY (`book_id`)
    REFERENCES `ecokat`.`book` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecokat`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecokat`.`book` (
  `book_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NULL,
  `author_id` INT NULL COMMENT '						',
  `page_num` INT NULL,
  `content` VARCHAR(45) NULL,
  `published_date` DATETIME NULL,
  `language` VARCHAR(45) NULL,
  `category_id` INT NULL COMMENT '			',
  `publisher` VARCHAR(45) NULL,
  `counter` INT NULL,
  `stock` INT NULL,
  `cost` DOUBLE NULL,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `image` BLOB NULL,
  PRIMARY KEY (`book_id`),
  INDEX `fk_category_id_idx` (`category_id` ASC),
  INDEX `fk_author_book_id_idx` (`author_id` ASC),
  CONSTRAINT `fk_category_book_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `ecokat`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_author_book_id`
    FOREIGN KEY (`author_id`)
    REFERENCES `ecokat`.`author` (`author_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecokat`.`rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecokat`.`rating` (
  `book_id` INT NOT NULL AUTO_INCREMENT,
  `count` INT NULL,
  `number` INT NULL,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`book_id`),
  CONSTRAINT `fk_book_rating_id`
    FOREIGN KEY (`book_id`)
    REFERENCES `ecokat`.`book` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecokat`.`user_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecokat`.`user_type` (
  `user_type_id` INT NOT NULL AUTO_INCREMENT,
  `user_type_name` VARCHAR(45) NULL,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`user_type_id`),
  UNIQUE INDEX `user_type_id_UNIQUE` (`user_type_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecokat`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecokat`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `adress` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `mail` VARCHAR(45) NULL,
  `birth_date` DATETIME NULL,
  `user_type_id` INT NULL,
  `update_time` DATETIME NULL,
  `create_time` DATETIME NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_category_id_idx` (`user_type_id` ASC),
  CONSTRAINT `fk_user_type_id`
    FOREIGN KEY (`user_type_id`)
    REFERENCES `ecokat`.`user_type` (`user_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecokat`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecokat`.`comment` (
  `book_id` INT NULL,
  `comment` VARCHAR(45) NULL,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  INDEX `fk_book_id_idx` (`book_id` ASC),
  CONSTRAINT `fk_book_comment_id`
    FOREIGN KEY (`book_id`)
    REFERENCES `ecokat`.`book` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecokat`.`sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecokat`.`sale` (
  `user_id` INT NULL,
  `book_id` INT NULL,
  `name` VARCHAR(45) NULL,
  `number` INT NULL,
  `cost` FLOAT NULL,
  `sale_id` INT NOT NULL,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`sale_id`),
  INDEX `fk_user_id_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_sale_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecokat`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_book_sale_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecokat`.`book` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecokat`.`favorite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecokat`.`favorite` (
  `user_id` INT NULL,
  `book_id` INT NULL,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `favorite_id` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_user_id_idx` (`user_id` ASC),
  PRIMARY KEY (`favorite_id`),
  INDEX `fk_book_id_idx` (`book_id` ASC),
  CONSTRAINT `fk_book_favorite_id`
    FOREIGN KEY (`book_id`)
    REFERENCES `ecokat`.`book` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_favorite_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecokat`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecokat`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecokat`.`comment` (
  `book_id` INT NULL,
  `comment` VARCHAR(45) NULL,
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  INDEX `fk_book_id_idx` (`book_id` ASC),
  CONSTRAINT `fk_book_comment_id`
    FOREIGN KEY (`book_id`)
    REFERENCES `ecokat`.`book` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
